
#line 3 "sff_scanner.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[219] =
    {   0,
        0,    0,    3,    3,    0,    0,    0,    0,    0,    0,
       70,   68,    8,    9,   68,   10,   68,   68,   68,   36,
       68,   11,   65,   65,   42,   40,   41,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   37,   68,
       68,    3,    5,   69,   24,   22,   23,   69,   32,   30,
       31,   33,   69,   35,   30,   35,   35,   34,    8,   43,
       38,   46,   45,    0,    0,   65,   67,    2,    0,   67,
        0,   65,   44,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   39,   47,
        0,    1,    3,    4,    4,    6,   24,   26,   19,   19,

       25,   26,   17,   21,   15,   16,   12,   14,   13,   18,
       32,   33,   33,   29,   19,   19,   29,   17,   29,   15,
       16,   12,   14,   13,   18,    0,    0,    0,    0,    0,
        7,   66,   59,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   50,   64,   64,   64,   64,   19,    0,
       20,   28,   27,    0,    0,    0,    0,    0,    0,    0,
       67,   64,   64,   64,   64,   64,   56,   64,   64,   64,
       64,   64,   64,   64,   57,   19,    0,   35,    0,    0,
       64,   54,   64,   64,   58,   64,   64,   64,   64,   64,
       64,   55,   35,   35,   35,   64,   64,   63,   64,   64,

       52,   49,   64,   61,   62,   64,   64,   60,   64,   64,
       48,   64,   64,   64,   64,   53,   51,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    1,    1,
        1,    8,    9,   10,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   16,   16,   17,    1,   18,
       19,   20,   21,   22,   23,   23,   23,   23,   24,   23,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   26,   25,   25,
       27,   28,   29,   30,   25,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   40,   40,   41,   42,   43,
       44,   45,   40,   46,   47,   48,   49,   50,   40,   51,
       52,   40,    1,   53,    1,   54,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        5,    5,    6,    7,    7,    7,    1,    1,    1,    1,
        8,    8,    9,    9,   10,   10,   11,   12,    8,    8,
        9,    9,    9,    9,    9,    9,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,    1,    1
    } ;

static yyconst flex_int16_t yy_base[238] =
    {   0,
        0,  496,   52,   53,   54,   59,   62,   64,   66,   69,
      501,  503,  498,  503,  480,  503,  491,   55,   64,  503,
       69,   58,   87,   92,  503,  489,  503,    0,  453,  451,
       29,  450,  462,  457,   45,  442,   70,   70,  437,  470,
      485,    0,  503,  102,    0,  503,  503,  125,    0,  503,
      503,   82,  163,  503,  503,  102,  201,  503,  485,  503,
      503,  503,  503,  108,  113,  118,  128,  503,  483,  134,
        0,  150,  503,    0,  433,  440,  448,  439,  432,  439,
      438,  445,  429,  428,  106,   89,  433,  425,  503,  503,
      470,  503,    0,  503,  118,  503,    0,  503,  166,  122,

      503,    0,  503,  503,  503,  503,  503,  503,  503,  503,
        0,  503,  443,  503,  169,  171,    0,  503,  232,  503,
      503,  503,  503,  503,  503,  459,  453,  450,  210,  465,
      503,    0,    0,  426,  435,  418,  432,  416,  417,  417,
      425,  414,  423,    0,  409,  375,  376,  352,  173,    0,
        0,  503,  503,  369,   88,  360,  124,  346,   39,  186,
      189,  320,  308,  298,  291,  295,    0,  271,  213,  199,
      213,  206,  200,  196,    0,  503,  143,  503,  150,  178,
      210,    0,  199,  204,    0,  202,  200,  185,  183,  183,
      192,    0,  216,  206,  203,  175,  173,    0,  171,  162,

        0,    0,  145,    0,    0,  157,  153,    0,  143,  143,
        0,  137,  111,   98,   51,    0,    0,  503,  262,  274,
      286,  298,  306,  316,  328,  340,  352,  363,  375,  385,
      397,  403,  406,  408,  420,  432,  444
    } ;

static yyconst flex_int16_t yy_def[238] =
    {   0,
      218,    1,  219,  219,  220,  220,  221,  221,  222,  222,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  218,  218,
      224,  225,  218,  226,  227,  218,  218,  228,  229,  218,
      218,  218,  230,  218,  218,  218,  230,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  231,  218,
      232,  218,  218,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  218,  218,
      224,  218,  225,  218,  226,  218,  227,  218,  218,  218,

      218,  233,  218,  218,  218,  218,  218,  218,  218,  218,
      229,  218,  218,  218,  218,  218,  233,  218,  234,  218,
      218,  218,  218,  218,  218,  235,  236,  237,  218,  231,
      218,  232,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  218,  233,
      233,  218,  218,  235,  235,  236,  236,  237,  237,  218,
      218,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  218,  235,  218,  236,  237,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  235,  236,  237,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,    0,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218
    } ;

static yyconst flex_int16_t yy_nxt[558] =
    {   0,
       12,   13,   14,   15,   16,   12,   17,   18,   19,   20,
       19,   21,   22,   23,   24,   24,   12,   25,   26,   27,
       12,   12,   28,   28,   28,   28,   12,   12,   12,   12,
       29,   30,   31,   32,   28,   33,   28,   34,   35,   28,
       28,   28,   28,   36,   28,   28,   37,   38,   28,   28,
       28,   28,   39,   40,   43,   43,   46,  180,   47,   44,
       44,   46,   62,   47,   50,   68,   50,  178,   55,   77,
       69,   55,   78,   63,   51,   64,   51,   65,   66,   66,
       82,   48,   67,   67,   67,  217,   48,   83,   52,   53,
       52,   53,   56,   57,   58,   56,   57,   58,   70,  177,

       65,   65,   65,   70,   85,   72,   72,   72,   87,   95,
      112,  113,   71,  126,   96,   88,  178,   86,  127,  145,
      128,   67,   67,   67,   70,   95,   65,   65,   65,   70,
       96,   72,   72,   72,  146,  149,  149,   71,   99,  100,
      179,   67,   67,   67,  216,  101,  143,   67,   67,   67,
      102,  129,  178,  144,  155,  103,  104,  129,  215,  105,
      106,   70,  129,   72,   72,   72,  157,  107,  129,  214,
      108,  193,  109,  213,  110,  102,  115,  116,  194,  149,
      149,  212,  149,  149,  149,  149,  176,  176,  117,  211,
      210,  150,  209,  118,  150,  119,  159,  120,  121,  161,

      161,  161,  161,  161,  161,  122,  195,  208,  123,  207,
      124,  206,  125,  117,  115,  116,  150,  205,  160,  150,
      160,  159,  157,  161,  161,  161,  117,  155,  204,  203,
      202,  118,  201,  119,  200,  120,  121,  199,  198,  197,
      196,  192,  191,  122,  190,  189,  123,  188,  124,  187,
      125,  117,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   54,   54,

       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       74,   74,   74,  186,   74,   74,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   93,  185,
       93,  184,   93,   93,   93,   93,   93,   93,   93,   93,
       94,  183,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   97,  182,  181,   97,   97,   97,   97,   97,
       97,   97,   97,   98,  159,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,  111,  157,  111,  111,  111,
      155,  111,  111,  111,  111,  114,  175,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  130,  130,  130,

      130,  130,  130,  130,  130,  130,  130,  130,  130,  132,
      174,  132,  151,  173,  151,  153,  153,  153,  153,  153,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  131,  159,  157,
      155,  112,   92,  148,  147,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  131,   59,   92,   90,   89,
       84,   81,   80,   79,   76,   75,   73,   61,   60,   59,

      218,   41,   11,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218
    } ;

static yyconst flex_int16_t yy_chk[558] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,  159,    5,    3,
        4,    6,   18,    6,    7,   22,    8,  159,    9,   31,
       22,   10,   31,   18,    7,   19,    8,   19,   19,   19,
       35,    5,   21,   21,   21,  215,    6,   35,    7,    7,
        8,    8,    9,    9,    9,   10,   10,   10,   23,  155,

       23,   23,   23,   24,   37,   24,   24,   24,   38,   44,
       52,   52,   23,   56,   44,   38,  155,   37,   56,   86,
       56,   64,   64,   64,   65,   95,   65,   65,   65,   66,
       95,   66,   66,   66,   86,  100,  100,   23,   48,   48,
      157,   67,   67,   67,  214,   48,   85,   70,   70,   70,
       48,   67,  157,   85,  177,   48,   48,   70,  213,   48,
       48,   72,   67,   72,   72,   72,  179,   48,   70,  212,
       48,  177,   48,  210,   48,   48,   53,   53,  179,   99,
       99,  209,  115,  115,  116,  116,  149,  149,   53,  207,
      206,   99,  203,   53,  115,   53,  180,   53,   53,  160,

      160,  160,  161,  161,  161,   53,  180,  200,   53,  199,
       53,  197,   53,   53,   57,   57,   99,  196,  129,  115,
      129,  195,  194,  129,  129,  129,   57,  193,  191,  190,
      189,   57,  188,   57,  187,   57,   57,  186,  184,  183,
      181,  174,  173,   57,  172,  171,   57,  170,   57,  169,
       57,   57,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      223,  223,  223,  168,  223,  223,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  225,  166,
      225,  165,  225,  225,  225,  225,  225,  225,  225,  225,
      226,  164,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  227,  163,  162,  227,  227,  227,  227,  227,
      227,  227,  227,  228,  158,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  229,  156,  229,  229,  229,
      154,  229,  229,  229,  229,  230,  148,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  232,
      147,  232,  233,  146,  233,  234,  234,  234,  234,  234,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  145,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  130,  128,  127,
      126,  113,   91,   88,   87,   84,   83,   82,   81,   80,
       79,   78,   77,   76,   75,   69,   59,   41,   40,   39,
       36,   34,   33,   32,   30,   29,   26,   17,   15,   13,

       11,    2,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[70] =
    {   0,
1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sff_scanner.ll"
/*
 *  This file is part of Siena, a wide-area event notification system.
 *  See http://www.inf.usi.ch/carzaniga/siena/
 *  
 *  Author: Antonio Carzaniga
 *  See the file AUTHORS for full details. 
 *  
 *  Copyright (C) 1998-2003 University of Colorado
 *  
 *  Siena is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  Siena is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 */
#line 26 "sff_scanner.ll"
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#if HAVE_UNISTD_H
#include <unistd.h>
#else
int isatty(int i) {
    return 0
}
#endif

#include <string>
#include <cstdlib>

#include "yysfftypes.h"
/* "yysfftypes.h" must be #included before "sff_parser.h" */
#include "sff_parser.hh"

#define YY_NO_UNPUT

std::string yysfffname = ""; /* Current source file name */
extern int yyerror (const char *);

extern void sff_parser_prompt();
extern void sff_parser_incomplete_command();

static int yyin_is_interactive = -1;

int sff_scanner_is_interactive() {
    if (yyin_is_interactive == -1) {
	if (!yyin) 
	    yyin = stdin;
        int fd = fileno(yyin);
	if (fd < 0) {
	    yyin_is_interactive = 0;
	} else {
	    yyin_is_interactive = isatty(fd);
	}
    }
    return yyin_is_interactive;
}

int sff_scanner_open(const char * fname) {
    if (fname != 0 && strcmp (fname, "-")) {
        yysfffname = fname;
        yyin = fopen(fname, "r");
	yyin_is_interactive = 0;
    } else {
	yysfffname = "{standard input}";
        yyin = stdin;
	yyin_is_interactive = -1;
    }
    yylineno = 1;
    return yyin == NULL;
}

int sff_scanner_close() {
    if (yyin != NULL && yyin != stdin) {
	int res = fclose(yyin);
	yyin = NULL;
	return res;
    } else 
	return 0;
}

#define RET(x) {yylval->nlin = yylineno; yylval->fname = & yysfffname;sff_parser_incomplete_command();};return(x)

/* Parts of a regular expressions. not_bracket is simply "everything but
   a bracket", but flex versions > 2.5.4 do not like two consecutive
   brackets in the input file!

   When parsing a regex, we don't want the / to be a terminator if
   it is within a bracket, i.e. /[abc/def]/ must be a valid regex.
   This is like sed, but unlike perl.  For this reason, we define one
   start conditions for brackets, that eats a 'bracket_elem' at a time.
   Note that a bracket is started with "["\^?\]? in order to eat the
   initial caret and a literal closing bracket.

   Also note that we want to parse escapes differently in strings and
   regexes, which is why we need a different token:

   0) Of course the above handling of brackets does not belong in strings.
   1) \b (bell, ASCII 7) is not supported in regexes.
   2) Unrecognized escapes (e.g. \< or \b itself) must be passed down
      to the regex matcher, rather than stripped. 
   3) We give an error if a regex is multiline unless each line is
      \-terminated.  In the future this may be extended to strings.

   coll_class is something like Perl's \[: .*? :\] and it can be
   "dissected" this way:

	"[:"			begin the sequence
	(\]|			closing bracket not preceded by :
	\:{not_bracket}|	or : not followed by closing bracket
	[^\]:])*		or any other char -- ad libitum
	":"+\]			and the end of the sequence		*/
/* 
 *  mutually exclusive states 
 */

#line 799 "sff_scanner.cc"

#define INITIAL 0
#define comment 1
#define strlit 2
#define regex 3
#define bracket 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 157 "sff_scanner.ll"


#line 994 "sff_scanner.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 219 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 503 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 159 "sff_scanner.ll"
{ const char * nlin; const char * fname;
                          if ((nlin = strtok(yytext, "\n#\t")) != NULL &&
                              (fname = strtok(NULL, " \t\"")) != NULL) {
			      yylineno = strtol(nlin, NULL, 10);
			      yysfffname = fname;
                          }
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 167 "sff_scanner.ll"
BEGIN(comment);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 168 "sff_scanner.ll"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 169 "sff_scanner.ll"
;
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 170 "sff_scanner.ll"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 171 "sff_scanner.ll"
BEGIN(INITIAL);
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 173 "sff_scanner.ll"
;		
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 175 "sff_scanner.ll"
; 
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 176 "sff_scanner.ll"
{ if (sff_scanner_is_interactive()) 
			      sff_parser_prompt(); };
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 179 "sff_scanner.ll"
{ yylval->str_v = new std::string(); BEGIN(strlit); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 180 "sff_scanner.ll"
{ yylval->str_v = new std::string(); BEGIN(regex); }
	YY_BREAK

/* More specific rules come first, so that they win over the generic "\\."
     rule below.  */
case 12:
YY_RULE_SETUP
#line 185 "sff_scanner.ll"
*yylval->str_v += '\n';
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 186 "sff_scanner.ll"
*yylval->str_v += '\t';
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 187 "sff_scanner.ll"
*yylval->str_v += '\r';
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 188 "sff_scanner.ll"
*yylval->str_v += '\e';
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 189 "sff_scanner.ll"
*yylval->str_v += '\f';
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 190 "sff_scanner.ll"
*yylval->str_v += '\a';
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 191 "sff_scanner.ll"
*yylval->str_v += '\v';
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 192 "sff_scanner.ll"
{ char *c = yytext + 1; /* skip '\\' */
                  *yylval->str_v += (char)(strtoul(c, NULL, 8) % 256); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 194 "sff_scanner.ll"
{ char *c = yytext + (yytext[1] == '0' ? 3 : 2); /* skip "\\0x" */
                  *yylval->str_v += (char)(strtoul(c, NULL, 16) % 256); }
	YY_BREAK


case 21:
YY_RULE_SETUP
#line 199 "sff_scanner.ll"
*yylval->str_v += '\b';
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 200 "sff_scanner.ll"
{ *yylval->str_v += '\n'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 201 "sff_scanner.ll"
{ BEGIN(INITIAL); RET(STR_v); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 202 "sff_scanner.ll"
{ yylval->str_v->append(yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 203 "sff_scanner.ll"
*yylval->str_v += '\?';
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 204 "sff_scanner.ll"
*yylval->str_v += yytext[1];
	YY_BREAK


/* A regex is very similar to a string literal, but unrecognized escapes
     are passed to the regex parser for further interpretation.  In addition,
     \cX sequences are recognized to mean Ctrl-X.  */
case 27:
YY_RULE_SETUP
#line 211 "sff_scanner.ll"
*yylval->str_v += (char) (yytext[2] ^ 96);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 212 "sff_scanner.ll"
*yylval->str_v += (char) (yytext[2] ^ 64);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 213 "sff_scanner.ll"
{ yylval->str_v->append(yytext); }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 214 "sff_scanner.ll"
{ yyerror ("new-line in regex"); BEGIN(INITIAL);
			      RET (REGEX_V); }
	YY_BREAK


case 31:
YY_RULE_SETUP
#line 219 "sff_scanner.ll"
{ BEGIN(INITIAL); RET(REGEX_V); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 220 "sff_scanner.ll"
{ yylval->str_v->append(yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 221 "sff_scanner.ll"
{ yylval->str_v->append(yytext); BEGIN (bracket); }
	YY_BREAK


case 34:
YY_RULE_SETUP
#line 225 "sff_scanner.ll"
{ yylval->str_v->append(yytext); BEGIN(regex); }
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 226 "sff_scanner.ll"
{ yylval->str_v->append(yytext); }
	YY_BREAK

case 36:
YY_RULE_SETUP
#line 229 "sff_scanner.ll"
RET(AND_op);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 230 "sff_scanner.ll"
RET(OR_op);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 231 "sff_scanner.ll"
RET(AND_op);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 232 "sff_scanner.ll"
RET(OR_op);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 233 "sff_scanner.ll"
RET(EQ_op);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 234 "sff_scanner.ll"
RET(GT_op);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 235 "sff_scanner.ll"
RET(LT_op);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 236 "sff_scanner.ll"
RET(NE_op);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 237 "sff_scanner.ll"
RET(PF_op);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 238 "sff_scanner.ll"
RET(SF_op);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 239 "sff_scanner.ll"
RET(SS_op);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 240 "sff_scanner.ll"
RET(RE_op);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 242 "sff_scanner.ll"
RET(IFCONFIG_kw);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 243 "sff_scanner.ll"
RET(SELECT_kw);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 244 "sff_scanner.ll"
RET(SET_kw);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 245 "sff_scanner.ll"
RET(CONSOLIDATE_kw);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 246 "sff_scanner.ll"
RET(OUTPUT_kw);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 247 "sff_scanner.ll"
RET(STATISTICS_kw);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 248 "sff_scanner.ll"
RET(CLEAR_kw);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 249 "sff_scanner.ll"
RET(TIMER_kw);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 250 "sff_scanner.ll"
RET(HELP_kw);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 252 "sff_scanner.ll"
{ yylval->bool_v = true; RET(BOOL_v); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 253 "sff_scanner.ll"
{ yylval->bool_v = false; RET(BOOL_v); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 255 "sff_scanner.ll"
RET(ANY_kw);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 256 "sff_scanner.ll"
RET(INTEGER_kw);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 257 "sff_scanner.ll"
RET(STRING_kw);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 258 "sff_scanner.ll"
RET(BOOLEAN_kw);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 259 "sff_scanner.ll"
RET(DOUBLE_kw);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 261 "sff_scanner.ll"
{ yylval->str_v = new std::string(yytext); RET(ID_v); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 263 "sff_scanner.ll"
{ yylval->int_v = strtoll(yytext, NULL, 10); RET(INT_v); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 265 "sff_scanner.ll"
{ yylval->int_v = strtoul(yytext, NULL, 16); RET(INT_v); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 267 "sff_scanner.ll"
{ yylval->double_v = strtod(yytext, NULL); RET(DOUBLE_v); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 269 "sff_scanner.ll"
RET(*yytext);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 271 "sff_scanner.ll"
ECHO;
	YY_BREAK
#line 1465 "sff_scanner.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(strlit):
case YY_STATE_EOF(regex):
case YY_STATE_EOF(bracket):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 219 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 219 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 218);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 1;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 271 "sff_scanner.ll"



int yywrap() { return 1; }

